name: Build Frida Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files in out directory
        run: dir .\out

      - name: Run hexreplace
        run: .\win\hexreplace.exe .\out frida-server.exe 74657374 74657374

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frida-patched
          path: .\out\frida-server.exe
