name: Build Basic Windows Frida
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Frida
        uses: actions/checkout@v4
        with:
          repository: frida/frida
          submodules: recursive
          path: frida

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install meson ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure and Build
        run: |
          cd frida
          .\configure.cmd
          .\make.cmd

      - name: Upload frida-server
        uses: actions/upload-artifact@v4
        with:
          name: frida-server
          path: frida/build/frida-server.exe
